name: clean_architecture_poktani
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc : ^9.1.1
  equatable: ^2.0.5
  get_it: ^8.0.3
  intl: ^0.20.2
  floor: ^1.4.2
  retrofit: ^4.5.0
  flutter_hooks: ^0.21.2
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0
  logger: ^2.6.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  dartz:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^9.2.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.7


flutter:
  uses-material-design: true
  assets:
    - assets/farm_illustration.png
    - assets/sukses.png
    - assets/sms.png
    - assets/placeholder.png
    - assets/farm_illustration_new.png
    - assets/banner.png
    - assets/user.png
    - assets/background.png
    - assets/pestisida.png
    - assets/pupuk.png
    - assets/tanaman.png
    - assets/rawr.png
    - assets/Group.png
    - assets/splash.png